#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'pydocstyle==1.0.0','console_scripts','pydocstyle'
__requires__ = 'pydocstyle==1.0.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('pydocstyle==1.0.0', 'console_scripts', 'pydocstyle')()
    )
